#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run the Next.js build command
npm run build

# Check if the build was successful
if [ $? -ne 0 ]; then
  echo "Build failed. Aborting push."
  exit 1
else
  echo "Build successful. Proceeding with push."
fi
